= Puppet, JRuby and Windows
:published_at: 2017-XX-XX
:hp-tags: jruby, windows, puppet
:hp-alt-title: Using Puppet with JRuby on Windows

== Introduction

https://nnn-dev.github.io/2017/10/27/Using-J-Rby-on-Windows.html[In my previous post], I have installed JRuby on Windows.
I want to use it to test puppet without installed it.

== Installing Puppet

Install puppet as a gem
[source,dos]	
> gem install puppet

Test it

[source,dos]
> puppet --version
NameError: undefined method `read_uint32' for class `FFI::Pointer'

== JRuby-FFI vs Ruby-FFI

FFI is embedded with JRuby but it is not the same as https://rubygems.org/gems/ffi[ffi] gem.

Modify the puppet executable on %JRUBY_HOME%/bin with this code:

[[puppet]]
[source,ruby]
----
#! jruby
#
# This file was generated by RubyGems.
#
# The application 'puppet' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

class ::FFI::Pointer
 ['16','32','64'].each do |nb|
  ['uint','int'].each do |type|
	alias_method "read_#{type}#{nb}".to_sym, "get_#{type}#{nb}".to_sym
	alias_method "write_#{type}#{nb}".to_sym, "put_#{type}#{nb}".to_sym
  end
 end
end

load Gem.activate_bin_path('puppet', 'puppet', version)
----

Test it

[source,dos]
> puppet --version
no such file to load -- win32/process

== Installing dependencies

Some specific dependencies for Windows are needed for Puppet on Windows.
These dependencies are not installed automatically.

Dependencies:
* win32-dir
* win32-security
* win32-process
* jruby-win32ole
* win32-service

[source,dos]
> gem install win32-dir win32-process jruby-win32ole
> gem install win32-security -v 0.4.0
> gem install win32-service -v 0.8.8

We don't install the last version of win32-service and win32-security because its depends of ffi-win32-extensions (not compatible with puppet).

Test it

[source,dos]
> puppet --version
[...]
5.3.2

It works! But with some warnings...

== Remove warnings ==

If you are some warnings like

[source,dos]
interpolation_support.rb:43: warning: `-' after local variable or literal is int
interpolation_support.rb:43: warning: even though it seems like unary operator
interpolation_support.rb:84: warning: `+' after local variable or literal is int
interpolation_support.rb:84: warning: even though it seems like unary operator
interpolation_support.rb:84: warning: `-' after local variable or literal is int

You can remove warnings with launching ruby with verbose level to *0*.

[source,dos]
> set JRUBY_OPTS='-W0'
> puppet --version
4.10.0


